#!/bin/env python

bld.program(target='test_block',
  source = bld.path.ant_glob('block/**/*.cpp'),
  use = ['cu', 'catch'],
  defines = ['CU_TEST'])

bld.program(target='test_unifying_block_input_stream',
  source = bld.path.ant_glob('unifying_block_input_stream/**/*.cpp'),
  use = ['cu', 'catch'],
  defines = ['CU_TEST'])
