#!/bin/env python

def options(opt):
  opt.recurse('vendor')

def configure(conf):
  conf.recurse('vendor')

def build(bld):
  bld.recurse('vendor')

  bld.program(target='test_block',
    source = bld.path.ant_glob('block/**/*.cpp'),
    use = ['cu', 'catch'],
    defines = ['CU_TEST'])

  bld.program(target='test_unifying_block_input_stream',
    source = bld.path.ant_glob('unifying_block_input_stream/**/*.cpp'),
    use = ['cu', 'catch'],
    defines = ['CU_TEST'])

  bld.program(target='test_endianness',
    source = bld.path.ant_glob('endianness/**/*.cpp'),
    use = ['cu', 'catch'],
    defines = ['CU_TEST'])
